INSERT INTO books (title, author, year, genre) VALUES
    ('The Great Gatsby', 'F. Scott Fitzgerald', 1925, 'Fiction'),
    ('To Kill a Mockingbird', 'Harper Lee', 1960, 'Fiction'),
    ('1984', 'George Orwell', 1949, 'Dystopian'),
    ('Pride and Prejudice', 'Jane Austen', 1813, 'Romance'),
    ('The Catcher in the Rye', 'J.D. Salinger', 1951, 'Fiction'),
    ('The Hobbit', 'J.R.R. Tolkien', 1937, 'Fantasy'),
    ('Fahrenheit 451', 'Ray Bradbury', 1953, 'Dystopian'),
    ('Moby Dick', 'Herman Melville', 1851, 'Adventure'),
    ('War and Peace', 'Leo Tolstoy', 1869, 'Historical'),
    ('Crime and Punishment', 'Fyodor Dostoevsky', 1866, 'Crime'),
    ('The Odyssey', 'Homer', -800, 'Epic'),
    ('Great Expectations', 'Charles Dickens', 1861, 'Fiction'),
    ('Ulysses', 'James Joyce', 1922, 'Modernist'),
    ('The Divine Comedy', 'Dante Alighieri', 1320, 'Epic'),
    ('Hamlet', 'William Shakespeare', 1603, 'Tragedy'),
    ('The Brothers Karamazov', 'Fyodor Dostoevsky', 1880, 'Philosophical'),
    ('One Hundred Years of Solitude', 'Gabriel Garcia Marquez', 1967, 'Magic Realism'),
    ('The Iliad', 'Homer', -750, 'Epic'),
    ('Brave New World', 'Aldous Huxley', 1932, 'Dystopian'),
    ('The Count of Monte Cristo', 'Alexandre Dumas', 1844, 'Adventure'),
    ('Les Misérables', 'Victor Hugo', 1862, 'Historical'),
    ('Anna Karenina', 'Leo Tolstoy', 1877, 'Romance'),
    ('The Sound and the Fury', 'William Faulkner', 1929, 'Fiction'),
    ('In Search of Lost Time', 'Marcel Proust', 1913, 'Modernist'),
    ('Don Quixote', 'Miguel de Cervantes', 1615, 'Adventure');